services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=notesapp
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - dbURL=mongodb://mongo:27017/notesapp
      - JWT_SECRET=your_jwt_secret_here
      - PORT=5000
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80" # Changed to 3000 to avoid potential conflicts
    environment:
      - VITE_APP_API_URL=http://localhost:5000
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data:
